### ISSUE TITLE
Unexpected text input after promoting the user to enter a number.

### ISSUE THREAD

**Issue by Mohammed-alhasan** [leggant/ProfPracticeGroupProject#13]
![rpi_1024x](https://user-images.githubusercontent.com/50258432/81647966-02b07700-9482-11ea-83c4-70da0852b8bf.png)

**Comment by leggant** [comment]
Huh........ Are you using an up to date version of the program?  Have you synchronised your pull request?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Mohammed-alhasan** [comment]
the problem occurred after adding the loop to the code but the  problem is i cant find anything in line 69,71 that prompts me to enter a text

**Comment by leggant** [comment]
Not sure what it happening with this but I think the random 34 located on line 126 could have caused the error.

![image](https://user-images.githubusercontent.com/61127354/81755285-7bf4ac00-950c-11ea-953c-f91da42c7994.png)
