### ISSUE TITLE
What does Moto Mean?

### ISSUE THREAD

**Issue by leggant** [leggant/ProfPracticeGroupProject#8]
There is a line of text in some of the Console.WriteLine("Moto"); statements - what is that?  
![image](https://user-images.githubusercontent.com/61127354/81355659-45d9b580-9123-11ea-8e1d-4109a9d6f5b6.png)

Can these strings be added to the external text files to make the code tidier or is that going to take to long to do??  If everyone just wants to hard code the strings into the main file that's all good, I will remove the array and external text files.

**Comment by Mohammed-alhasan** [comment]
This is just a random text to get the feel of how the program going to be .
i added these random text as we are waiting for the text files,so they are just temporary text .
we can modify these later and make it look more official .
@leggant

**Comment by leggant** [comment]
@chooke1994 ok sweet.  Thanks i just wasnt sure :)
